### ISSUE TITLE
Empty window in Wayland on NVIDIA (GNOME 44)

### ISSUE THREAD

**Issue by develop7** [flathub/com.plexamp.Plexamp#44]
Repro:

1. `flatpak run com.plex.Plexamp`

Expected: a Plexamp window shows up

Instead: empty rectangle is rendered, see below
![image](https://user-images.githubusercontent.com/89889/231407745-6daf9c52-8c6d-40d4-8543-d3c0b133169e.png)

<details><summary>Console output:</summary>

```
$ flatpak run com.plexamp.Plexamp 
WAYLAND enabled, using the Wayland Electron backend
Using NVIDIA on Wayland, applying workaround
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization -ozone-platform=wayland --disable-gpu-sandbox --enable-features=UseSkiaRenderer,UseOzonePlatform,WaylandWindowDecorations
LaunchProcess: failed to execvp:
xdg-settings
[3:0412/105934.519646:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0412/105934.519686:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Main: Window state x:0 y:0 w:270 h:515 fullscreen:undefined maximized:undefined
Main: Display bounds x:2560 y:0 w:1920 h:1080
Main: Centering offscreen window x:0 y:0 w:270 h:515
Main: Display 5 bounds x:0 y:246 w:2560 h:1440
Main: Display 6 bounds x:2560 y:0 w:1920 h:1080
Started Media Service: false
[50:0412/105934.570333:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
Linux: Registering MPRIS service.
[50:0412/105934.612763:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[50:0412/105934.612780:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[50:0412/105934.612791:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[50:0412/105934.612796:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[50:0412/105934.612803:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[50:0412/105934.612810:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
[50:0412/105934.612873:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[50:0412/105934.612879:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[50:0412/105934.613033:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[50:0412/105934.613128:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[50:0412/105934.613133:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[50:0412/105934.613689:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[50:0412/105934.613707:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[50:0412/105934.613713:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[50:0412/105934.616689:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[50:0412/105934.616698:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[50:0412/105934.616705:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[50:0412/105934.616709:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[50:0412/105934.616713:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[50:0412/105934.616716:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
[3:0412/105934.896666:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=133
[88:0412/105934.932906:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
[88:0412/105934.959882:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[88:0412/105934.959899:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[88:0412/105934.959907:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[88:0412/105934.959911:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[88:0412/105934.959916:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[88:0412/105934.959920:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
[88:0412/105934.959972:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[88:0412/105934.959988:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[88:0412/105934.960075:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[88:0412/105934.960082:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[88:0412/105934.960591:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[88:0412/105934.960607:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[88:0412/105934.960613:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[88:0412/105934.964036:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[88:0412/105934.964045:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[88:0412/105934.964050:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[88:0412/105934.964053:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[88:0412/105934.964057:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[88:0412/105934.964060:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
[3:0412/105935.247556:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=133
[105:0412/105935.279861:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
[105:0412/105935.305370:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[105:0412/105935.305383:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[105:0412/105935.305403:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[105:0412/105935.305407:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[105:0412/105935.305410:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[105:0412/105935.305414:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
[105:0412/105935.305458:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[105:0412/105935.305462:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[105:0412/105935.305557:ERROR:shared_context_state.cc(538)] Failed to make current since context is marked as lost
[105:0412/105935.305561:ERROR:skia_output_surface_impl_on_gpu.cc(1744)] Failed to make current.
[105:0412/105935.305783:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[105:0412/105935.305796:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[105:0412/105935.305800:ERROR:raster_decoder.cc(1252)]   RasterDecoderImpl: Context lost during MakeCurrent.
[105:0412/105935.314041:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[105:0412/105935.314051:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage SCANOUT
[105:0412/105935.314057:ERROR:gbm_pixmap_wayland.cc(76)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[105:0412/105935.314061:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 768x1024, RGBA_8888, usage GPU_READ
[105:0412/105935.314065:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[105:0412/105935.314069:ERROR:shared_image_factory.cc(697)] CreateSharedImage: could not create backing.
APPIMAGE env is not defined, current application is not an AppImage
[3:0412/105935.596825:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=133
[59:0412/105935.633307:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Couldn't install shortcut for MediaPlayPause.
Couldn't install shortcut for MediaPreviousTrack.
Couldn't install shortcut for MediaNextTrack.
Couldn't install shortcut for MediaStop.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at App.<anonymous> (/app/bin/plexamp/resources/app.asar/main.js:2:468945)
    at App.emit (node:events:526:28)
    at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:33:560)
    at BrowserWindow.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at App.<anonymous> (/app/bin/plexamp/resources/app.asar/main.js:2:468860)
    at App.emit (node:events:526:28)
    at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:33:619)
    at BrowserWindow.emit (node:events:526:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at App.<anonymous> (/app/bin/plexamp/resources/app.asar/main.js:2:468945)
    at App.emit (node:events:526:28)
    at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:33:560)
    at BrowserWindow.emit (node:events:526:28)
```
</details>

System info:

```
$ inxi -xx -S
System:
  Host: t-rex Kernel: 6.2.9-1-default arch: x86_64 bits: 64 compiler: gcc
    v: 13.0.1 Desktop: GNOME v: 44.0 tk: GTK v: 3.24.37 wm: gnome-shell dm: GDM
    Distro: openSUSE Tumbleweed 20230410
```

**Comment by simonxciv** [comment]
Hi @develop7 and thanks for the detailed report!

Could you please confirm the Plexamp version where you're seeing this behaviour? I've been unable to reproduce the problem on a fresh Fedora install with Gnome 44, Wayland, an nvidia 1650 with proprietary drivers installed, and the latest Plexamp flatpak release (4.6.2-r2).

**Comment by develop7** [comment]
```
$ flatpak info com.plexamp.Plexamp 

Plexamp - Plexamp - A beautiful Plex music player for audiophiles, curators,
and hipsters.

          ID: com.plexamp.Plexamp
         Ref: app/com.plexamp.Plexamp/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.6.2-r2
     License: LicenseRef-proprietary=https://www.plex.tv/en-gb/about/privacy-legal/plex-terms-of-service/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 225,0 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 8cc7328684ace54c8eb0d88c3a8b495f5c92d30905ad34dfde64114c1cdaec2a
      Parent: a42e00cbac7f3d822ec783d826f70babefa24353013396276c0ecf30eca1afcf
     Subject: Update Flathub badge in README.md (#43) (9a24d2e4)
        Date: 2023-04-12 19:35:33 +0000
```

**Comment by develop7** [comment]
My bad. I've been tinkering with Plexamp myself before and had a `com.plex.Plexamp.desktop` at `~/.local/share/applications` with few changes which seemed to be overriding original one. Sorry for bothering and thank you for your time & attention!
